name: Trigger Lambda on Main Merge

on:
  push:
    branches:
      - main

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --invocation-type Event \
            --payload '{}' \
            response.json
          cat response.json
